<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-3LM0TE9V" ignored="0" name="EmployeeAPITest" tests="17" failures="2" timestamp="03 Aug 2019 08:02:04 GMT" time="26.871" errors="0">
  <testcase name="checkHeader" time="0.012" classname="com.employeeapi.tests.TC001_Get_All_Employees"/>
  <testcase name="checkResponseBody" time="0.311" classname="com.employeeapi.tests.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employeeapi.tests.TC001_Get_All_Employees"/>
  <testcase name="checkStatusLine" time="0.0" classname="com.employeeapi.tests.TC001_Get_All_Employees"/>
  <testcase name="checkHeader" time="0.004" classname="com.employeeapi.tests.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkResponseBody" time="0.003" classname="com.employeeapi.tests.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.003" classname="com.employeeapi.tests.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkStatusLine" time="0.004" classname="com.employeeapi.tests.TC002_Get_Single_Employee_Record"/>
  <testcase name="checkHeader" time="0.004" classname="com.employeeapi.tests.TC003_Post_Employee_Record"/>
  <testcase name="checkResponseBody" time="0.006" classname="com.employeeapi.tests.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.tests.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:50)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkStatusCode" time="0.003" classname="com.employeeapi.tests.TC003_Post_Employee_Record"/>
  <testcase name="checkStatusLine" time="0.002" classname="com.employeeapi.tests.TC003_Post_Employee_Record"/>
  <testcase name="checkHeader" time="0.004" classname="com.employeeapi.tests.TC004_Put_Employee_Record"/>
  <testcase name="checkResponseBody" time="0.003" classname="com.employeeapi.tests.TC004_Put_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employeeapi.tests.TC004_Put_Employee_Record"/>
  <testcase name="checkStatusLine" time="0.002" classname="com.employeeapi.tests.TC004_Put_Employee_Record"/>
  <testcase name="checkResponseBody" time="0.004" classname="com.employeeapi.tests.TC005_Delete_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employeeapi.tests.TC005_Delete_Employee_Record.checkResponseBody(TC005_Delete_Employee_Record.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
</testsuite> <!-- EmployeeAPITest -->
